spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/moneylog}
    username: ${SPRING_DATASOURCE_USERNAME:moneylog}
    password: ${SPRING_DATASOURCE_PASSWORD:moneylog}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
