spring:
  application:
    name: money-log-server
  profiles:
    default: local

server:
  forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

moneylog:
  api:
    legacy-v1:
      enabled: true
